version: "3.9"

services:
  db:
    image: postgres:15
    container_name: measurement_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: measurements
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:


  ingestion:


  frontend:


